export const ADD_PRODUCT = 'ADD_PRODUCT';
export const SUCCES_ADD_PRODUCT = 'SUCCES_ADD_PRODUCT';
export const ERROR_ADD_PRODUCT = 'ERROR_ADD_PRODUCT';

export const DOWNLOAD_START_PRODUCTS = 'DOWNLOAD_START_PRODUCTS';
export const DOWNLOAD_SUCESS_PRODUCTS = 'DOWNLOAD_SUCESS_PRODUCTS';
export const DOWNLOAD_ERROR_PRODUCTS = 'DOWNLOAD_ERROR_PRODUCTS';

export const GET_PRODUCT_DELETE = 'GET_PRODUCT_DELETE';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

export const GET_PRODUCT_EDIT = 'GET_PRODUCT_EDIT';
export const STAR_EDIT_PRODUCT = 'STAR_EDIT_PRODUCT';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';